Fix ordering of inits to unbreak unikernels runtimes
Currently, starting a mirage app results in the following error:

    Fatal error: exception Invalid_argument("Key.get: Called too early. Please delay this call after cmdliner's evaluation.")

This is a regression introduced in 167d14fbc489bed071ef6f97b200588193402abf.
I have added a test to make sure this won't happen anymore.