functoria: Better type-error for the start function
With this change, the error message is no longer about the pattern and
looks clearer.

Unfortunately, the location is still within generated code. This also
requires adding the `'a io` type in the prelude.

    File "bin/mirage/mirage/main.ml", lines 300-305, characters 3-12:
    Error: This expression has type (unit, 'a) result Lwt.t
           but an expression was expected of type unit start = unit Lwt.t
           Type (unit, 'a) result is not compatible with type unit