mirage_runtime: call malloc_trim on every major GC cycle
OCaml 5.x uses 2 memory allocators: `malloc(3)/free(3)` and
`mmap(2)/munmap(2)`. Memory released by `free(3)` may not be immediately
available for allocation by `mmap(2)`.
If a program allocates both large and small values it may crash in
`caml_fatal_error` even after calling `Gc.compact()`.

Call `malloc_trim(3)` at the end of every major cycle (i.e.
`Gc.full_major()` and `Gc.compact()` will call it).
This ensures that memory is eventually released back to the OS,
and available for `mmap(2)`.

A testcase which crashes without this patch is available in
`mirage-skeleton`, confirmed to crash with the `unix` backend.

This is a best-effort fix, since `malloc_trim` is non-standard,
and may not be available on all Unix backends.
Even on Linux if a different memory allocator is used (e.g. `jemalloc`),
then `malloc_trim` will free memory from the `glibc` allocator, and thus
be a no-op.

Before:
```
$ ulimit -v 440000;OCAMLRUNPARAM=d=1 dist/memory)
[...]
2026-07-07T08:28:26+01:00: [INFO] [application] Done
2026-07-07T08:28:26+01:00: [INFO] [application] Allocating a total of 36372480 words
2026-07-07T08:28:26+01:00: [INFO] [application] Allocating 141802 * 254 = 36017708 words
2026-07-07T08:28:26+01:00: [INFO] [application] Done
2026-07-07T08:28:26+01:00: [INFO] [application] Allocating a total of 36372480 words
Fatal error: caml_skiplist_insert: out of memory

$ /bin/time dist/memory
5.34user 0.20system 0:05.55elapsed 99%CPU (0avgtext+0avgdata 583236maxresident)k
0inputs+0outputs (0major+145230minor)pagefaults 0swaps
```

After:
```
time dist/memory
4.92user 0.94system 0:05.87elapsed 99%CPU (0avgtext+0avgdata 295536maxresident)k
0inputs+0outputs (0major+446311minor)pagefaults 0swaps
```

Signed-off-by: Edwin Török <edwin@tarides.com>