Fix cmdliner term generation for keys with the same name but different defaults
Since https://github.com/mirage/mirage/pull/1162 the (CLI) name is not enough
to distinguish between keys. This means that we build a cmdliner term with
multiple keys having the same name. In that case cmdliner will explode at
runtime with something like:

    Fatal error: exception Invalid_argument("option name --interface defined twice
      (doc strings are 'The network interface listened by the unikernel.  ' and
      'The network interface listened by the unikernel.  ')")

This happens when we call `mirage --help`, `mirage describe`, `mirage clean`
with partial implementation choices (e.g. without a corresponding
`mirage configure`).